global using CitizenFX.Core;
global using FxEvents;
global using Newtonsoft.Json;
global using Perserverance.Client.GameInterface.Events;
global using Perserverance.Shared.Models;
global using Perserverance.Shared.Models.SnailyCAD;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Runtime.Serialization;
global using System.Threading.Tasks;
global using static CitizenFX.Core.Native.API;
global using Perserverance.Shared.Attributes;
