global using CitizenFX.Core;
global using CitizenFX.Core.UI;
global using FxEvents;
global using Newtonsoft.Json;
global using Perserverance.Client.GameInterface.Events;
global using Perserverance.Shared.Attributes;
global using Perserverance.Shared.Enums;
global using Perserverance.Shared.Models;
global using Perserverance.Shared.Models.Hud;
global using Perserverance.Shared.Models.SnailyCAD;
global using System;
global using System.Collections.Generic;
global using System.Drawing;
global using System.Linq;
global using System.Threading.Tasks;
global using static CitizenFX.Core.Native.API;
global using Font = CitizenFX.Core.UI.Font;