namespace Perseverance.Shared.Models.SnailyCAD
{
    public class Leo
    {
        public string dispatch { get; set; }
        public string myOfficers { get; set; }
        public string myOfficerLogs { get; set; }
        public string createOfficer { get; set; }
        public string editOfficer { get; set; }
        public string deleteOfficer { get; set; }
        public string callsign { get; set; }
        public string department { get; set; }
        public string officer { get; set; }
        public string officerName { get; set; }
        public string noOfficers { get; set; }
        public string selectOfficer { get; set; }
        public string totalTime { get; set; }
        public string startedAt { get; set; }
        public string endedAt { get; set; }
        public string notEndedYet { get; set; }
        public string status { get; set; }
        public string citizen { get; set; }
        public string postal { get; set; }
        public string notes { get; set; }
        public string violations { get; set; }
        public string division { get; set; }
        public string createTicket { get; set; }
        public string createArrestReport { get; set; }
        public string createWrittenWarning { get; set; }
        public string createBolo { get; set; }
        public string nameSearch { get; set; }
        public string addressSearch { get; set; }
        public string notepad { get; set; }
        public string plateSearch { get; set; }
        public string weaponSearch { get; set; }
        public string activeOfficer { get; set; }
        public string activeOfficers { get; set; }
        public string updateAOP { get; set; }
        public string utilityPanel { get; set; }
        public string noActiveOfficers { get; set; }
        public string badgeNumber { get; set; }
        public string areaOfPlay { get; set; }
        public string plateOrVin { get; set; }
        public string serialNumber { get; set; }
        public string results { get; set; }
        public string owner { get; set; }
        public string weaponNotFound { get; set; }
        public string vehicleNotFound { get; set; }
        public string fullAddress { get; set; }
        public string viewInNameSearch { get; set; }
        public string noResults { get; set; }
        public string enterAddress { get; set; }
        public string noVehiclesCitizen { get; set; }
        public string noWeaponsCitizen { get; set; }
        public string noTicketsCitizen { get; set; }
        public string noWrittenWarnings { get; set; }
        public string noArrestReports { get; set; }
        public string tickets { get; set; }
        public string writtenWarnings { get; set; }
        public string arrestReports { get; set; }
        public string nameNotFound { get; set; }
        public string createWarrant { get; set; }
        public string citizenDead { get; set; }
        public string hasWarrants { get; set; }
        public string rank { get; set; }
        public string position { get; set; }
        public string officerLogs { get; set; }
        public string disableSignal100 { get; set; }
        public string enableSignal100 { get; set; }
        public string signal100enabled { get; set; }
        public string records { get; set; }
        public string suspendLicense { get; set; }
        public string deleteRecord { get; set; }
        public string image { get; set; }
        public string panicButton { get; set; }
        public string panicButtonLeo { get; set; }
        public string viewAllResults { get; set; }
        public string vehicleReportedStolen { get; set; }
        public string impoundLot { get; set; }
        public string noImpoundedVehicles { get; set; }
        public string allowCheckout { get; set; }
        public string plate { get; set; }
        public string color { get; set; }
        public string location { get; set; }
        public string model { get; set; }
        public string incidents { get; set; }
        public string createIncident { get; set; }
        public string caseNumber { get; set; }
        public string firearmsInvolved { get; set; }
        public string injuriesOrFatalities { get; set; }
        public string arrestsMade { get; set; }
        public string involvedOfficers { get; set; }
        public string noIncidents { get; set; }
        public string deleteIncident { get; set; }
        public string toggleRecords { get; set; }
        public string toggleVehiclesWeapons { get; set; }
        public string unmerge { get; set; }
        public string merge { get; set; }
        public string suspended { get; set; }
        public string jailTime { get; set; }
        public string arrested { get; set; }
        public string timeOut { get; set; }
        public string jail { get; set; }
        public string release { get; set; }
        public string noImprisonedCitizens { get; set; }
        public string bailPostedBy { get; set; }
        public string noPenalCodesSelected { get; set; }
        public string penalCode { get; set; }
        public string total { get; set; }
        public string fines { get; set; }
        public string bail { get; set; }
        public string editLicenses { get; set; }
        public string callHistory { get; set; }
        public string linkToIncident { get; set; }
        public string caseNumbers { get; set; }
        public string hideBlips { get; set; }
        public string showBlips { get; set; }
        public string citizenLogs { get; set; }
        public string noCitizenLogs { get; set; }
        public string revoke { get; set; }
        public string warrants { get; set; }
        public string noWarrants { get; set; }
        public string revokeWarrant { get; set; }
        public string releaseCitizen { get; set; }
        public string reportedStolen { get; set; }
        public string pendingAccessDepartment { get; set; }
        public string pendingAccessDepartmentNoDefault { get; set; }
        public string editTicket { get; set; }
        public string editArrestReport { get; set; }
        public string editWrittenWarning { get; set; }
        public string quantity { get; set; }
        public string illegal { get; set; }
        public string add { get; set; }
        public string noSeizedItems { get; set; }
        public string editSeizedItem { get; set; }
        public string addSeizedItem { get; set; }
        public string seizedItems { get; set; }
        public string callsignPreview { get; set; }
        public string activeIncidents { get; set; }
        public string noActiveIncidents { get; set; }
        public string incident { get; set; }
        public string endIncident { get; set; }
        public string end { get; set; }
        public string manageIncident { get; set; }
        public string radioChannel { get; set; }
        public string manageRadioChannel { get; set; }
        public string noIncidentEvents { get; set; }
        public string viewCall { get; set; }
        public string situationCode { get; set; }
        public string mergeOfficers { get; set; }
        public string manageVehicleFlags { get; set; }
        public string manageCitizenFlags { get; set; }
        public string successCreateWarrant { get; set; }
        public string successCreateTicket { get; set; }
        public string successCreateArrestReport { get; set; }
        public string successCreateWarning { get; set; }
        public string goOnDuty { get; set; }
        public string goOffDuty { get; set; }
        public string officers { get; set; }
        public string callsign1 { get; set; }
        public string callsign2 { get; set; }
        public string license { get; set; }
        public string otherFields { get; set; }
        public string manageCustomFields { get; set; }
        public string dmv { get; set; }
        public string unitsInvolved { get; set; }
        public string customFieldSearch { get; set; }
        public string noCustomFieldResults { get; set; }
        public string customField { get; set; }
        public string query { get; set; }
        public string penalCodes { get; set; }
        public string noPenalCodes { get; set; }
        public string noVehiclesPendingApprovalInDmv { get; set; }
        public string citizenIsConfidential { get; set; }
        public string unitQualifications { get; set; }
        public string addQualification { get; set; }
        public string noQualifications { get; set; }
        public string qualification { get; set; }
        public string suspend { get; set; }
        public string unsuspend { get; set; }
        public string deleteQualification { get; set; }
        public string assignedAt { get; set; }
        public string suspendedOn { get; set; }
        public string unitAwards { get; set; }
        public string noAwards { get; set; }
        public string addAward { get; set; }
        public string award { get; set; }
        public string activeCall { get; set; }
        public string arrestReportLogs { get; set; }
        public string activeUnits { get; set; }
        public string noActiveUnits { get; set; }
        public string player { get; set; }
        public string cadUsername { get; set; }
        public string emsFd { get; set; }
        public string leo { get; set; }
        public string weapon { get; set; }
        public string vehicle { get; set; }
        public string onFoot { get; set; }
        public string licensePlate { get; set; }
        public string identifier { get; set; }
        public string togglePlayer { get; set; }
        public string vehicleBoloPlaced { get; set; }
        public string citizenBoloPlaced { get; set; }
        public string noNotes { get; set; }
        public string addNote { get; set; }
        public string manageNote { get; set; }
        public string text { get; set; }
        public string deleteNote { get; set; }
        public string dropToUnassignFromIncident { get; set; }
        public string switchDivisionCallsign { get; set; }
        public string createCitizen { get; set; }
        public string unit { get; set; }
        public string createVehicle { get; set; }
        public string tones { get; set; }
        public string notesInfo { get; set; }
        public string emsFdTone { get; set; }
        public string leoTone { get; set; }
        public string sendTone { get; set; }
        public string toneSuccess { get; set; }
        public string toneNotification { get; set; }
        public string activeWarrants { get; set; }
        public string noActiveWarrants { get; set; }
        public string paymentStatus { get; set; }
        public string recordPaid { get; set; }
        public string showCalls { get; set; }
        public string hideCalls { get; set; }
        public string showUnitsOnly { get; set; }
        public string showAllPlayers { get; set; }
        public string totalCost { get; set; }
        public string warningApplicable { get; set; }
        public string impounded { get; set; }
        public string impoundVehicle { get; set; }
        public string impoundedBy { get; set; }
        public string impoundedAt { get; set; }
        public string endsOn { get; set; }
        public string assignedToCall { get; set; }
        public string assignedToCallWithType { get; set; }
        public string warrantCreatedButApprovalRequired { get; set; }
        public string suspendDriversLicense { get; set; }
        public string suspendPilotLicense { get; set; }
        public string suspendWaterLicense { get; set; }
        public string suspendFirearmsLicense { get; set; }
        public string endDate { get; set; }
        public string patrolVehicle { get; set; }
        public string callUpdated { get; set; }
        public string alert_deleteNote { get; set; }
        public string alert_deleteQualification { get; set; }
        public string vehicleImpoundLocation { get; set; }
        public string steamId { get; set; }
        public string discordId { get; set; }
        public string citizenMissing { get; set; }
        public string declareFound { get; set; }
        public string declareMissing { get; set; }
        public string manageTones { get; set; }
        public string noExistingTones { get; set; }
        public string toneRevoked { get; set; }
        public string toneRevokedText { get; set; }
        public string involvedUnits { get; set; }
        public string addUnit { get; set; }
        public string unassign { get; set; }
        public string manageAddressFlags { get; set; }
        public string temporaryUnit { get; set; }
        public string createTemporaryUnit { get; set; }
        public string identifiers { get; set; }
        public string identifiersInfo { get; set; }
        public string hours { get; set; }
        public string firstSeen { get; set; }
        public string lastSeen { get; set; }
        public string deputies { get; set; }
        public string mergeDeputies { get; set; }
        public string call { get; set; }
        public string connections { get; set; }
        public string viewIncident { get; set; }
        public string businessSearch { get; set; }
        public string vehicles { get; set; }
        public string businessHasNoVehicles { get; set; }
        public string viewInVehicleSearch { get; set; }
        public string alert_endIncident { get; set; }
        public string alert_deleteRecord { get; set; }
        public string alert_deleteOfficer { get; set; }
        public string alert_allowCheckout { get; set; }
        public string alert_deleteIncident { get; set; }
        public string alert_revokeWarrant { get; set; }
    }

}
